### PR TITLE
Add Win7 support.

### PR DESCRIPTION
**Pull request by jenatali**
Add Win7 support. This should address #30. I've tested D3D9, DXGI, and Vulkan apps on Win7, both in realtime and from an ETL file. The interesting thing here is adding support for Win7's DxgKrnl/DWM provider data, which is somewhat different from Win8+. Additionally, I verified that PresentMon correctly handles DWM-off scenarios, which don't (really) exist on Win8+.

I did my best to regression test what I could. Let me know if you have specific scenarios I should try, or if you find things that are broken.

### CODE REVIEW

**Comment by jenatali** [comment]
@jdm3, friendly ping. Have you had a chance to look at this yet?

**Comment by jdm3** [comment]
Sorry, somehow I had it in my head this was done :)  Will pull it this morning!  Do you need a new release or is master branch fine?

**Comment by jenatali** [comment]
I don't "need" a new release, but this seems like a big enough feature to warrant one in my mind. No rush on that though.

**Comment by jdm3** [comment]
New release: https://github.com/GameTechDev/PresentMon/releases/tag/v1.2.0

Thanks for the reminder, and sorry for the delay!

**Pull request merged**
